[program:bakutrack-laravel-worker]
directory=/var/www/bakutrack/backend
command=/usr/bin/php artisan queue:work redis --sleep=3 --tries=3 --timeout=120
autostart=true
autorestart=true
user=www-data
numprocs=1
stdout_logfile=/var/log/supervisor/bakutrack-laravel-worker.log
stderr_logfile=/var/log/supervisor/bakutrack-laravel-worker-error.log
